#!/bin/sh
# Run each test and compare
# against known good output

EXE=../bin/ac0

# Build our compiler if needed
if [ ! -f "$EXE" ]
then (cd ../alc; make)
fi

# Try to use each input source file
for i in test*.al
# We can't do anything if there's no file to test against
do if [ ! -f "out/$i" -a ! -f "err/$i" ]
   then echo "Can't run test on $i, no output or error file!"; exit 1

   # Output file: compile the source, run it and
   # capture the output, and compare it against
   # the known-good output
   else if [ -f "out/$i" ]
        then
	  # Print the test name, compile it with our compiler
          echo -n $i
	  $EXE -o out.q $i && qbe out.q > out.s && cc -o bin out.s
          ./bin > trial

  	  # Compare this agains the correct output
          cmp -s "out/$i" trial

	  # If different, announce failure
          # and print out the difference
          if [ "$?" -eq "1" ]
          then echo ": failed"
            diff -c "out/$i" trial
	    # Stop if our 1st argument is "stop"
	    if [ "$#" -eq 1 ] && [ $1 = "stop" ]
	    then exit 1
	    fi
            echo

	  # No failure, so announce success
          else echo ": OK"
          fi

   # Error file: compile the source and
   # capture the error messages. Compare
   # against the known-bad output. Same
   # mechanism as before
   else if [ -f "err/$i" ]
        then
          echo -n $i
	  $EXE -o /dev/null $i 2> trial
          cmp -s "err/$i" trial
          if [ "$?" -eq "1" ]
          then echo ": failed"
            diff -c "err/$i" trial
            echo
          else echo ": OK"
          fi
        fi
     fi
   fi
   rm -f bin out.[qs] trial
done
